name: "efficientnet-lite4"
platform: "onnxruntime_onnx"

max_batch_size: 0

input [
  {
    name: "images:0"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 224, 224, 3 ]
    reshape { shape: [ 1, 224, 224, 3 ] }
  }
]

output [
  {
    name: "Softmax:0"
    data_type: TYPE_FP32
    dims: [ 1, 1000 ]
    label_filename: "enlite4_labels.txt"
  }
]
